version: 0.0
os: linux

# 파일배포 관련 설정
files:
  - source: /
    destination: /home/ec2-user/back
    overwrite: yes
file_exists_behavior: OVERWRITE

# 권한 설정
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user

hooks:
  AfterInstall:
    - location: scripts/stop.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: ec2-user